repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Check if all files follow the rustfmt style
        entry: .scripts/pre-commit.sh
        language: system
        stages: [commit]
        pass_filenames: false

      - id: add commit to .git-blame-ignore-revs
        name: add-commit
        description: Adds the current git commit SHA, author and message to .git-blame-ignore-revs and amend
        entry: .scripts/post-commit.sh
        language: system
        stages: [post-commit]
        pass_filenames: false
