[package]
name = "codectrl"
version = "0.1.0"
edition = "2021"
authors = ["pwnCtrl <contact@pwnctrl.com>", "Samuel Boyden <s.boyden@pwnctrl.com>"]
description = "A source code analytic tool. Using egui version 0.16."
rust-version = "1.58.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codectrl_gui = { path = "./codectrl-gui", optional = "true" }

[features]
default = ["codectrl_gui"]
