[package]
name = "codectrl"
version = "0.1.0"
edition = "2021"
authors = ["pwnCtrl <contact@pwnctrl.com>", "Samuel Boyden <s.boyden@pwnctrl.com>", "Sebestyen Morris <s.morris@pwnctrl.com>"]
description = "A source code analytic tool. Using egui version 0.15.0."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = "2.33"
code_ctrl_logger = { path = "loggers/rust-logger", default-features = false, features = ["types-only"] }
eframe = "0.15"
egui = { version = "0.15", features = ["persistence", "multi_threaded"] }
egui_glow = "0.15"
epi = "0.15"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
serde_json = "1.0"
server = { path = "./server" }
tokio = { version = "1.13", default-features = false, features = ["net", "rt-multi-thread", "io-util", "macros"] }

[build-dependencies]
chrono = "0.4"
toml = "0.5"