[package]
name = "codectrl"
version = "0.1.0"
edition = "2021"
authors = ["pwnCtrl <contact@pwnctrl.com>", "Samuel Boyden <sam@stboyden.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.0"
server = { path = "./server" }
tokio = { version = "1.0", features = ["full"] }
egui = "0.15"
egui_glow = "0.15"
