[package]
name = "codectrl"
version = "0.1.0"
edition = "2021"
authors = ["Authentura <contact@authentura.com>", "Samuel Boyden <s.boyden@authentura.com>"]
description = "A source code analytic tool. Using egui version 0.16."
license = "MIT"
rust-version = "1.58.1"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codectrl_gui = { path = "./codectrl-gui" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
eframe = "0.16"

[package.metadata.deb]
name = "codectrl"
maintainer = "Samuel Boyden <s.boyden@authentura.com>"
copyright = "2022, Authentura <contact@authentura.com>"
license-file = ["LICENSE", "4"]
assets = [
  ["README.md", "usr/share/doc/codectrl/README", "644"]
]

[package.metadata.rpm]
package = "codectrl"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
codectrl = { path = "/usr/bin/codectrl" }
