[package]
name = "codectrl"
version = "0.1.0"
edition = "2021"
authors = ["pwnCtrl <contact@pwnctrl.com>", "Samuel Boyden <sam@stboyden.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.0"
server = { path = "./server" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_cbor = "0.11"
tokio = { version = "1.0", features = ["full"] }
egui = { version = "0.15", features = ["persistence", "multi_threaded"] }
egui_glow = "0.15"
epi = "0.15"
eframe = "0.15"
