[package]
name = "codectrl_gui"
version = "0.1.0"
edition = "2021"
authors = [
    "Authentura <contact@authentura.com>",
    "Samuel Boyden <s.boyden@authentura.com>",
    "Sebestyen Morris <s.morris@authentura.com>",
    "Dasith Vidanage <d.vidanage@authentura.com>",
    "Balázs Cene (@bczsalba on Github) <bczsalba@gmail.com>"
]
description = "A source code analytic tool. Using egui version 0.16."
rust-version = "1.58.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
codectrl_logger = { git = "https://github.com/authentura/codectrl-rust-logger", default-features = false, features = ["types-only"] }
eframe = "0.16"
egui = { version = "0.16", features = ["persistence"] }
epi = { version = "0.16", features = ["persistence"] }
lazy_static = "1.4"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
# serde_json = "1.0"
# tree-sitter-highlight = "0.20.1"
# tree-sitter-cpp = "0.19.0"
# tree-sitter-rust = "0.20.1"
# tree-sitter-python = "0.19.1"
syntect = { version = "4.2", default-features = false, features = ["default-fancy"]}
xxhash-rust = { version = "0.8.3", features = ["xxh3"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
chrono = { version = "0.4", features = ["serde", "js-sys", "wasmbind"] }
console_error_panic_hook = "0.1"
js-sys = "0.3"
rfd = { version = "0.6", features = ["file-handle-inner"] }
tracing-wasm = "0.2"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
wasm_thread = "0.1"
web-sys = { version = "0.3", features = ["File", "FilePropertyBag", "console"]}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
chrono = { version = "0.4", features = ["serde"] }
codectrl_log_server = { path = "../codectrl-log-server" }
egui_glow = "0.16"
rfd = "0.6"
tokio = { version = "1.17", default-features = false, features = ["net", "rt-multi-thread", "io-util", "macros"] }

[build-dependencies]
chrono = "0.4"
toml = "0.5"
