name: Build
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-ubuntu-22-04:
    name: Build and Package for Ubuntu 22.04
    runs-on: ubuntu-latest
    container: ghcr.io/authentura/codectrl-ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - uses: dtolnay/rust-toolchain@stable

      - name: Fetch cache if already exists
        continue-on-error: true
        uses: actions/cache@v3
        id: has-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ubuntu-22-04-${{ hashFiles('**/Cargo.lock') }}

      - if: steps.has-cache.outputs.cache-hit != 'true'
        name: Install cargo-deb
        continue-on-error: true
        run: cargo install cargo-deb

      - if: steps.has-cache.outputs.cache-hit != 'true'
        name: Build and package CodeCTRL
        shell: bash
        run: |
          cargo deb

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ubuntu-22-04-${{ hashFiles('**/Cargo.lock') }}

      - name: Rename .deb
        run: ./find-and-rename-pkg.sh

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v3
        with:
          name: Ubuntu 22.04 package
          path: target/debian/*.deb

  package-fedora-latest:
    name: Package for latest stable Fedora
    runs-on: ubuntu-latest
    container: ghcr.io/authentura/codectrl-fedora-latest
    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - uses: dtolnay/rust-toolchain@stable

      - name: Fetch cached build
        uses: actions/cache@v3
        id: has-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: fedora-latest-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-generate-rpm
        continue-on-error: true
        run: cargo install cargo-generate-rpm

      - if: steps.has-cache.outputs.cache-hit != 'true'
        name: Build and package CodeCTRL
        shell: bash
        run: |
          cargo build --release
          cargo generate-rpm

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: fedora-latest-${{ hashFiles('**/Cargo.lock') }}

      - name: Rename .rpm
        run: ./find-and-rename-pkg.sh

      - name: Upload .rpm artifact
        uses: actions/upload-artifact@v3
        with:
          name: Fedora Latest package
          path: target/generate-rpm/*.rpm

  package-fedora-rawhide:
    name: Package for Fedora Rawhide
    runs-on: ubuntu-latest
    container: ghcr.io/authentura/codectrl-fedora-rawhide
    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - uses: dtolnay/rust-toolchain@stable

      - name: Fetch cached build
        uses: actions/cache@v3
        id: has-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: fedora-rawhide-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-generate-rpm
        continue-on-error: true
        run: cargo install cargo-generate-rpm

      - if: steps.has-cache.outputs.cache-hit != 'true'
        name: Build and package CodeCTRL
        shell: bash
        run: |
          cargo build --release
          cargo generate-rpm

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: fedora-rawhide-${{ hashFiles('**/Cargo.lock') }}

      - name: Rename .rpm
        run: ./find-and-rename-pkg.sh

      - name: Upload .rpm artifact
        uses: actions/upload-artifact@v3
        with:
          name: Fedora Rawhide package
          path: target/generate-rpm/*.rpm

  build-windows-latest:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch cache if already exists
        continue-on-error: true
        uses: actions/cache@v3
        id: windows-has-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-wix
        continue-on-error: true
        run: cargo install cargo-wix

      - name: Build CodeCTRL
        run: cargo build --release

      - name: Generate MSI
        run: cargo wix --nocapture

      - name: Upload .msi artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows installer package
          path: target/wix/*.msi

      - name: Cache binary
        uses: actions/cache@v3
        id: cache-binary
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
