name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch cache if already exists
        continue-on-error: true
        uses: actions/cache@v3
        id: has-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ hashFiles('**/Cargo.lock') }}

      - if: ${{ steps.has-cache.outputs.cache-hit == 'false' }}
        name: Bootstrap dependencies
        run: ./bootstrap-action.sh

      - if: ${{ steps.has-cache.outputs.cache-hit == 'false' }}
        uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-unknown-linux-musl

      - if: ${{ steps.has-cache.outputs.cache-hit == 'false' }}
        name: Build CodeCTRL
        run: PKG_CONFIG_SYSROOT_DIR="/" RUSTFLAGS="-Ctarget-feature=+crt-static" cargo build --release --target=x86_64-unknown-linux-musl

      - name: Strip binary
        run: strip -s target/x86_64-unknown-linux-musl/release/codectrl

      - name: Cache binary
        uses: actions/cache@v3
        id: cache-binary
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ hashFiles('**/Cargo.lock') }}

  package-ubuntu-22-04:
    name: Package for 22.04
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Fetch cached build
        uses: actions/cache@v3
        id: cache-binary
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ hashFiles('**/Cargo.lock') }}

      - name: Generate DEB file
        run: |
          cargo install cargo-deb
          cargo deb --no-build --no-strip --target x86_64-unknown-linux-musl

      - name: Rename .deb
        run: ./find-and-rename-pkg.sh

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v3
        with:
          name: Ubuntu 22.04 package
          path: target/x86_64-unknown-linux-musl/debian/*.deb

  package-fedora-latest:
    name: Package for latest stable Fedora
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch cached build
        uses: actions/cache@v3
        id: cache-binary
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ hashFiles('**/Cargo.lock') }}

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Prepare Docker image
        uses: ./.github/actions/run-fedora-latest
        with:
          command: echo Prepared Docker!

      - name: Generate RPM file
        uses: ./.github/actions/run-fedora-latest
        with:
          command: cargo generate-rpm --target x86_64-unknown-linux-musl

      - name: Rename .rpm
        uses: ./.github/actions/run-fedora-latest
        with:
          command: /find-and-rename-pkg.sh /github/workspace

      - name: Upload .rpm artifact
        uses: actions/upload-artifact@v3
        with:
          name: Fedora Latest package
          path: target/x86_64-unknown-linux-musl/generate-rpm/*.rpm

  package-fedora-rawhide:
    name: Package for Fedora Rawhide
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch cached build
        uses: actions/cache@v3
        id: cache-binary
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ hashFiles('**/Cargo.lock') }}

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Prepare Docker image
        uses: ./.github/actions/run-fedora-rawhide
        with:
          command: echo Prepared Docker!

      - name: Generate RPM file
        uses: ./.github/actions/run-fedora-rawhide
        with:
          command: cargo generate-rpm --target x86_64-unknown-linux-musl

      - name: Rename .rpm
        uses: ./.github/actions/run-fedora-rawhide
        with:
          command: /find-and-rename-pkg.sh /github/workspace

      - name: Upload .rpm artifact
        uses: actions/upload-artifact@v3
        with:
          name: Fedora Rawhide package
          path: target/x86_64-unknown-linux-musl/generate-rpm/*.rpm

  build-windows-latest:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch cache if already exists
        continue-on-error: true
        uses: actions/cache@v3
        id: has-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-wix
        run: cargo install cargo-wix

      - if: ${{ steps.has-cache.outputs.cache-hit == 'false' }}
        name: Build CodeCTRL
        run: cargo build --release

      - name: Generate MSI
        run: cargo wix --nocapture

      - name: Upload .msi artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows installer package
          path: target/wix/*.msi

      - name: Cache binary
        uses: actions/cache@v3
        id: cache-binary
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
