name: Build
on: [push, pull_request, release]

jobs:
  build-ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - name: Bootstrap Ubuntu
        run: ./bootstrap-action.sh
      - name: Build CodeCTRL and package
        run: cargo deb

  build-fedora-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build CodeCTRL
      - uses: ../actions/run-fedora-latest
        with:
          command: cargo build --release
      - name: Strip debugging symbols
      - uses: ../actions/run-fedora-latest
        with:
          command: strip -s target/release/codectrl
      - name: Build CodeCTRL and package
      - uses: ../actions/run-fedora-latest
        with:
          command: cargo generate-rpm
