name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Bootstrap dependencies
        run: ./bootstrap-action.sh

      - uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-unknown-linux-musl

      - name: Build CodeCTRL
        run: RUSTFLAGS="-Ctarget-feature=+crt-static" cargo build --release --target=x86_64-unknown-linux-musl

      - name: Strip binary
        run: strip -s target/x86_64-unknown-linux-gnu/release/codectrl

      - name: Cache binary
        uses: actions/cache@v3
        with:
          path: target/x86_64-unknown-linux-gnu/release/codectrl
          key: codectrl

  package-ubuntu-22-04:
    name: Package for 22.04
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Fetch cached build
        uses: actions/cache@v3
        with:
          restore-keys: codectrl

      - name: Generate DEB file
        run: |
          cargo install cargo-deb
          cargo deb --no-build --no-strip --target x86_64-unknown-linux-gnu

      - name: Rename .deb
        run: ./find-and-rename-pkg.sh

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v3
        with:
          name: Ubuntu 22.04 package
          path: target/debian/*.deb

  package-fedora-latest:
    name: Package for latest stable Fedora
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch cached build
        uses: actions/cache@v3
        with:
          restore-keys: codectrl

      - name: Prepare Docker image
        uses: ./.github/actions/run-fedora-latest
        with:
          command: echo Prepared Docker!

      - name: Generate RPM file
        uses: ./.github/actions/run-fedora-latest
        with:
          command: cargo generate-rpm --target-dir target/x86_64-unknown-linux-gnu/release

      - name: Rename .rpm
        uses: ./.github/actions/run-fedora-latest
        with:
          command: /find-and-rename-pkg.sh /github/workspace

      - name: Upload .rpm artifact
        uses: actions/upload-artifact@v3
        with:
          name: Fedora Latest package
          path: target/generate-rpm/*.rpm

  package-fedora-rawhide:
    name: Package for Fedora Rawhide
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch cached build
        uses: actions/cache@v3
        with:
          restore-keys: codectrl

      - name: Prepare Docker image
        uses: ./.github/actions/run-fedora-rawhide
        with:
          command: echo Prepared Docker!

      - name: Generate RPM file
        uses: ./.github/actions/run-fedora-rawhide
        with:
          command: cargo generate-rpm --target-dir target/x86_64-unknown-linux-gnu/release

      - name: Rename .rpm
        uses: ./.github/actions/run-fedora-rawhide
        with:
          command: /find-and-rename-pkg.sh /github/workspace

      - name: Upload .rpm artifact
        uses: actions/upload-artifact@v3
        with:
          name: Fedora Rawhide package
          path: target/generate-rpm/*.rpm

  build-windows-latest:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cargo-wix
        run: cargo install cargo-wix

      - name: Build CodeCTRL
        run: cargo build --release

      - name: Generate MSI
        run: cargo wix --nocapture

      - name: Upload .msi artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows installer package
          path: target/wix/*.msi
