name: Build
on: [push, pull_request]

jobs:
  build-ubuntu-22-04:
    name: Build for Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Bootstrap Ubuntu
        run: ./bootstrap-action.sh

      - name: Build CodeCTRL
        run: cargo build --release

      - name: Generate DEB file
        run: cargo deb

      - name: Rename .deb
        run: ./find-and-rename-pkg.sh

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v3
        with:
          name: Ubuntu 22.04 package
          path: target/debian/*.deb

  build-fedora-latest:
    name: Build for latest Fedora
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Docker image
        uses: ./.github/actions/run-fedora-latest
        with:
          command: echo Prepared Docker!

      - name: Build CodeCTRL
        uses: ./.github/actions/run-fedora-latest
        with:
          command: cargo build --release

      - name: Strip resulting binary
        uses: ./.github/actions/run-fedora-latest
        with:
          command: strip -s target/release/codectrl

      - name: Generate RPM file
        uses: ./.github/actions/run-fedora-latest
        with:
          command: cargo generate-rpm

      - name: Rename .rpm
        uses: ./.github/actions/run-fedora-latest
        with:
          command: /find-and-rename-pkg.sh /github/workspace

      - name: Upload .rpm artifact
        uses: actions/upload-artifact@v3
        with:
          name: Fedora Latest package
          path: target/generate-rpm/*.rpm

  build-fedora-rawhide:
    name: Build for Fedora Rawhide
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Docker image
        uses: ./.github/actions/run-fedora-rawhide
        with:
          command: echo Prepared Docker!

      - name: Build CodeCTRL
        uses: ./.github/actions/run-fedora-rawhide
        with:
          command: cargo build --release

      - name: Strip resulting binary
        uses: ./.github/actions/run-fedora-rawhide
        with:
          command: strip -s target/release/codectrl

      - name: Generate RPM file
        uses: ./.github/actions/run-fedora-rawhide
        with:
          command: cargo generate-rpm

      - name: Rename .rpm
        uses: ./.github/actions/run-fedora-rawhide
        with:
          command: /find-and-rename-pkg.sh /github/workspace

      - name: Upload .rpm artifact
        uses: actions/upload-artifact@v3
        with:
          name: Fedora Rawhide package
          path: target/generate-rpm/*.rpm

  build-windows-latest:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cargo-wix
        run: cargo install cargo-wix

      - name: Build CodeCTRL
        run: cargo build --release

      - name: Generate MSI
        run: cargo wix --nocapture

      - name: Upload .msi artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows installer package
          path: target/wix/*.msi
