name: Clippy Check
on: [push, pull_request]

jobs:
  clippy_check:
    name: cargo clippy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          - target: wasm32-unknown-unknown
          - components: clippy
      - name: Bootstrap Ubuntu
        run: ./bootstrap-action.sh
      - name: Run clippy check
        run: cargo clippy --release --all-features --all-targets
