name: Clippy Check
on:
  push:
    branches: [main]
  pull_request:

jobs:
  clippy_check:
    name: cargo clippy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly-2022-08-21
        with:
          target: wasm32-unknown-unknown
          components: clippy
      - name: Bootstrap Ubuntu
        run: sudo ./bootstrap-action.sh
      - name: Run clippy check
        run: cargo clippy --release --all-targets
