name: Auto-update Containers
on: [push, pull_request] # temporary until we have at least one build for each container

env:
  USERNAME: STBoyden
  CR_PAT: ${{ secrets.CR_PAT }}

jobs:
  build:
    name: Build and update containers
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Run build-and-upload-containers.sh
        run: ./build-and-upload-containers.sh ${{ env.USERNAME }}
