name: Auto-update Containers
on: [push] # temporary until we have at least one build for each container

jobs:
  build-ubuntu-latest:
    name: Build and push Ubuntu latest container
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: ubuntu-latest-{hash}
        continue-on-error: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./.github/actions/ubuntu-latest
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/authentura/codectrl-ubuntu-latest:latest

  build-ubuntu-20-04:
    name: Build and push Ubuntu 20.04 container
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: ubuntu-20-04-{hash}
        continue-on-error: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./.github/actions/ubuntu-20-04
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/authentura/codectrl-ubuntu-20-04:latest

  build-fedora-latest:
    name: Build and push latest Fedora container
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: fedora-latest-{hash}
        continue-on-error: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./.github/actions/fedora-latest
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/authentura/codectrl-fedora-latest:latest

  build-fedora-rawhide:
    name: Build and push Fedora Rawhide container
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: fedora-rawhide-{hash}
        continue-on-error: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./.github/actions/fedora-rawhide
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/authentura/codectrl-fedora-rawhide:latest
