name: Auto-update Containers
on: [push] # temporary until we have at least one build for each container

jobs:
  build-ubuntu-latest:
    name: Build and push Ubuntu latest container
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: ubuntu-latest
        continue-on-error: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        working-directory: ./.github/actions/ubuntu-latest
        run: |
          docker build -t authentura/codectrl-ubuntu-latest:latest .
          docker push ghcr.io/authentura/codectrl-ubuntu-latest:latest

      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: ubuntu-latest
        continue-on-error: true

  build-ubuntu-20-04:
    name: Build and push Ubuntu 20.04 container
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: ubuntu-22-04
        continue-on-error: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        working-directory: ./.github/actions/ubuntu-20-04
        run: |
          docker build -t authentura/codectrl-ubuntu-20-04:latest .
          docker push ghcr.io/authentura/codectrl-ubuntu-20-04:latest

      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: ubuntu-22-04
        continue-on-error: true

  build-fedora-latest:
    name: Build and push latest Fedora container
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: fedora-latest
        continue-on-error: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        working-directory: ./.github/actions/fedora-latest
        run: |
          docker build -t authentura/codectrl-fedora-latest:latest .
          docker push ghcr.io/authentura/codectrl-fedora-latest:latest

      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: fedora-latest
        continue-on-error: true

  build-fedora-rawhide:
    name: Build and push Fedora Rawhide container
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: fedora-rawhide
        continue-on-error: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        working-directory: ./.github/actions/fedora-rawhide
        run: |
          docker build -t authentura/codectrl-fedora-rawhide:latest .
          docker push ghcr.io/authentura/codectrl-fedora-rawhide:latest

      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: fedora-rawhide
        continue-on-error: true
